version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Create Directory"
          command: New-Item -ItemType Directory -Path ./bin
      - run:
          name: "Download Hugo v0.60.1"
          command: $ProgressPreference = "SilentlyContinue"; Invoke-WebRequest -Uri https://github.com/gohugoio/hugo/releases/download/v0.60.1/hugo_0.60.1_Windows-64bit.zip -OutFile ./bin/hugo_0.60.1_Windows-64bit.zip -UseBasicParsing; Expand-Archive -Path ./bin/hugo*.zip -DestinationPath ./bin
      - run:
          name: "Download NuGet v5.3.1"
          command: $ProgressPreference = "SilentlyContinue"; Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile ./bin/nuget.exe -UseBasicParsing
      - run:
          name: "Install the markdown-proofing NPM package"
          command: npm install -g markdown-proofing
      - run:
          name: "Test Spelling and Punctuation"
          command: npm test
      - run:
          name: "Generate Website"
          command: ./bin/hugo
      - run:
          name: "Package Website"
          command: ./bin/nuget pack -Version 1.0.$env:CIRCLE_BUILD_NUM -NoDefaultExcludes -NoPackageAnalysis
      - run:
          name: "Publish Website"
          command: ./bin/nuget push -source https://f.feedz.io/cvd/cvd-id-au/nuget/index.json -ApiKey $env:FEEDZ_API_KEY ./cvd.id.au.1.0.$env:CIRCLE_BUILD_NUM.nupkg
