version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            $ProgressPreference = "SilentlyContinue"
            New-Item -ItemType Directory -Path ./bin
            Invoke-WebRequest -Uri https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Windows-64bit.zip -OutFile ./bin/hugo.zip -UseBasicParsing
            Expand-Archive -Path ./bin/hugo.zip -DestinationPath ./bin
            Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile ./bin/nuget.exe -UseBasicParsing
            npm install -g markdown-proofing
      - run:
          name: "Build"
          command: ./bin/hugo
      - run:
          name: "Test"
          command: npm test
      - run:
          name: "Package"
          command: ./bin/nuget pack -Version 1.0.$env:CIRCLE_BUILD_NUM -NoDefaultExcludes -NoPackageAnalysis
      - run:
          name: "Publish"
          command: ./bin/nuget push -source https://f.feedz.io/cvd/cvd-id-au/nuget/index.json -ApiKey $env:FEEDZ_API_KEY ./cvd.id.au.1.0.$env:CIRCLE_BUILD_NUM.nupkg
