name = "cvd"
license = "MIT"
licenselink = ""
description = "Chris van Dal"
homepage = "https://cvd.id.au/"
tags = []
features = []
min_version = "0.55.6"

[author]
  name = "Chris van Dal"
  homepage = "https://cvd.id.au/"
